#!/usr/bin/env bash
# Records banner.py to an asciicast, then renders it to an SVG banner.
# Must be run from a real terminal (a controlling TTY) - termtosvg needs
# one to capture anything
#
# Usage: ./record.sh [theme] [speed] [loop-delay-ms]
# Themes (generated by themes/build_themes.py, one per file in
# themes/palettes/ - see themes/import_palettes.py): kanagawa_wave
# (default), plus 600+ more imported from mbadolato/iTerm2-Color-Schemes.
# Append "_once" to any of them (e.g. kanagawa_wave_once) to play once and
# freeze on the final frame instead of looping. Any termtosvg built-in
# template name also works (e.g. dracula, solarized_dark, solarized_light,
# xterm). speed is banner.py's typing-speed multiplier (default: 1.0).
# loop-delay-ms is how long (in milliseconds) the finished animation holds
# on its last frame before restarting the loop (default: 5000). Ignored in
# practice by "_once" themes, which freeze forever instead of looping.
#
# See also: themes/detect_terminal_theme.py (grab your live terminal's
# colors as a theme) and themes/add_background.py (center the result on a
# solid-color backdrop with a drop shadow).
set -euo pipefail
cd "$(dirname "$0")"

THEME="${1:-kanagawa_wave}"
SPEED="${2:-1.0}"
LOOP_DELAY_MS="${3:-5000}"
GEOMETRY="92x24"

if [ -f "themes/${THEME}.svg" ]; then
    TEMPLATE="themes/${THEME}.svg"
else
    TEMPLATE="$THEME"
fi

uvx termtosvg record demo.cast -c "uv run banner.py --speed $SPEED" -g "$GEOMETRY"
uvx termtosvg render demo.cast "banner-${THEME}.svg" -m 30 -D "$LOOP_DELAY_MS" -t "$TEMPLATE"

echo "Wrote demo.cast and banner-${THEME}.svg"
